// import "./01_基础类型";
// import "./02_接口";
// import "./03_函数类型";
// import "./04_类类型";
// import "./05_类";
// import "./06_继承";
// import "./07_多态";
// import "./08_修饰符";
// import "./09_readonly修饰符";
// import "./10_存取器";
// import "./11_静态成员";
// import "./12_抽象类";
// import "./13_函数";
// import "./14_可选参数和默认参数";
// import "./15_剩余参数";
// import "./16_函数重载";
// import "./17_泛型";
// import "./18_多个泛型参数的函数";
// import "./19_泛型接口";
// import "./20_泛型类";
import "./21_泛型约束";
document.write("hello world!");
